### ISSUE TITLE
请问是不是出故障了，不会接话了

### ISSUE THREAD

**Issue by redstoneleo** [ddiu8081/chatgpt-demo#193]
### Describe the bug

请问是不是出故障了，不会接话了

### Reproduction

问他“你是谁

### System Info

```Shell
null
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Thanks for taking the time to fill out this bug report! Please read this note otherwise your question may be closed directly:

- If the language of the README is English, it is best to use English to ask questions. This allows more people to search and participate in the issue.
- For Q&A, please ask your questions in the discussions and not in the issue, if the repo has Discussions
- Ensure the bug was not already reported by searching on GitHub under Issues.
  If you're unable to find an open issue addressing the problem, open a new one. Be sure to include:
  - A title and clear description.
  - As much relevant information as possible.
  - A code sample or an executable test case.

**Comment by liuyuxivapor** [comment]
被墙了大概是
