### ISSUE TITLE
现在黑色主题进去是白色的的界面会闪一下才变成黑色的主题

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#203]
### Additional context

现在黑色主题进去是白色的的界面会闪一下才变成黑色的主题

**Comment by ddiu8081** [comment]
Thanks for taking the time to fill out this bug report! Please read this note otherwise your question may be closed directly:

- If the language of the README is English, please use English to ask questions. This allows more people to search and participate in the issue.
- For Q&A, please ask your questions in the discussions and not in the issue, if the repo has Discussions
- Ensure the bug was not already reported by searching on GitHub under Issues.
  If you're unable to find an open issue addressing the problem, open a new one. Be sure to include:
  - A title and clear description.
  - As much relevant information as possible.
  - A code sample or an executable test case.
