### ISSUE TITLE
OpenAI Account is deactivated after using this demo

### ISSUE THREAD

**Issue by zhouyinchi** [ddiu8081/chatgpt-demo#250]
### Describe the bug

![image](https://user-images.githubusercontent.com/38196296/224647718-80e4970b-2a4d-4d3a-9d21-6bf5c01239f4.png)

### Reproduction

run this demo

### System Info

```Shell
macos
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
I've noticed that OpenAI seems to have recently raised its risk control level and started blocking accounts, but the site I deployed via Netlify is still available. This may not be caused by the repo itself.

Please make sure that you have not done the following (several times), which may result in account blocking:

1. Accessing the API from an unsupported location. e.g. China Mainland, Hong Kong. See [Supported countries](https://platform.openai.com/docs/supported-countries).
2. The entered text content violates the [Usage policies](https://platform.openai.com/docs/usage-policies).
3. Polling with multiple API Keys, which may be considered abusive.
4. OpenAI accounts are registered in bulk, and they have similar email addresses.

**Comment by AI-Rocket-Camp** [comment]
A WeChat group was set up for ChatGPT developers to discuss the following issues: 1. Openai api was blocked for unknown reasons; 2. How to choose an overseas server; 3. How to improve the access speed of domestic users; 4. Discussion on monetization related experience. Wait, for developers of the ChatGPT api ecosystem:
(搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai api不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：)
![WX20230401-184113@2x](https://user-images.githubusercontent.com/50973253/229284290-43c6b2a1-8410-44db-bb02-432db8c29679.png)

现在群聊接近二百人了，二维码也失效，请加微信AI-camp-666，然后拉进群
