### ISSUE TITLE
Optimize "to the bottom" button

### ISSUE THREAD

**Issue by CNSeniorious000** [ddiu8081/chatgpt-demo#344]
### Clear and concise description of the problem

v1版本下，在接收新消息时，会自动跟随着最新的消息，用一个限流的函数不停地触发置于底部，但存在两个问题

1. 由于都是平滑滚动，所以看起来文字上上下下的，不稳定（参考官方Web APP那种是稳定）
2. 用户不能在等回复的时候看上面的文本

### Suggested solution

1. 增加一个按钮，允许用户打开/关闭这个feature
2. 如果打开，使用不限流的函数不停触发瞬间滚动到底部
3. 当用户往上滑时，自动转换这个按钮的状态为不跟随

### Alternative

也可以只允许跟随/不跟随，但根据我个人的调研，大家是有这个需求的

### Additional context

我已经在我个人部署的版本中实现了这个功能，大家可以参考一下作为一个demo：

> [chat.muspimerol.site](https://chat.muspimerol.site/)

（暂时还没实现上面提的第3点，但这不难，很快可以实现）

如果我把这个feature整理了提个PR，能被merge吗

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
PR welcome, Thank you!

**Comment by CNSeniorious000** [comment]
Hi @ddiu8081, I submitted a #350 a few hours ago that adds a "stick-to-bottom" feature. Would you have time to review it? Thank you!

- I'm wondering if adding a button for this feature would be too big of a change for the project. What do you think?
- In fact, I’ve also considered implementing the "stick-to-bottom" feature using a double-click or long-press on the existing "scroll to bottom" button, but I decided against it due to factors such as the button being hidden when at the bottom. Do you have any thoughts on this?

I understand that most of the feature development is focused on the v2 branch right now, but I believe that v1 is still a remarkable project. It would be valuable to add some new features to it without compromising its simplicity. Would appreciate your opinion 👀

**Comment by ddiu8081** [comment]
I really like the idea and the final result.

In fact, this was my original idea for "scroll to top", "scroll to bottom" - double-click on the header to scroll to the top, and click on the cue bar above the input box to scroll to the bottom. As in the draft image on the left.

![shapes](https://user-images.githubusercontent.com/1998168/230283422-00527832-5614-4e2a-99dc-65e303e2ac68.png)

But it is true that the v1 version does not have a fixed header or footer,  so I accepted the right-hand draft solution - using a button fixed in the bottom right or bottom left corner.

When the "fixed bottom" feature is available, I prefer the latter option and have the button displayed all the time, as you have done.

I think in v1, you can delete the original two buttons in the bottom right corner and keep yours.

**Comment by CNSeniorious000** [comment]
Thank you for your positive feedback on my PR. I understand that your original idea was to use a double-click or click on the cue bar above the input box to scroll to the top or bottom, respectively. Since the v1 version does not have a fixed header or footer, the button fixed in the bottom right or bottom left corner was used instead.

Could you please confirm the following:

- Can I replace the existing "scroll to bottom" button with my "fixed bottom" button, which should always be displayed?
- Would you prefer that I remove the "scroll to top" button as well?

Thank you for your time and consideration. I look forward to your response.

**Comment by ddiu8081** [comment]
> Could you please confirm the following:

Yes, you can remove the existing "scroll to bottom" and "scroll to top" button.
